version: '3.1'

services:
  db:
    image: mysql:8.0 
    container_name: db_os
    restart: always 
    environment:
      MYSQL_ROOT_PASSWORD: example 
    ports: 
      - "3306:3306"
    volumes:
      - ./data:/var/lib/mysql
    networks:
      - mynet

  phpmyadmin:
    image: phpmyadmin 
    container_name: phpmyadmin_os
    restart: always 
    environment: 
      PMA_HOST: db 
      PMA_POST: 3306 
      MYSQL_ROOT_PASSWORD: example 
    ports:
      - "8000:80"
    depends_on:
      - db
    networks:
      - mynet

networks:
  mynet:
    driver: bridge 
